spring:
  application:
    name: 论坛系统
  datasource:   # 配置数据源
    url: jdbc:mysql://127.0.0.1:3307/forum_db?characterEncoding=utf8&useSSL=false  # 数据库连接串
    username: root
    password: 000000
    driver-class-name: com.mysql.jdbc.Driver # 数据库连接驱动
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #Springfox-Swagger兼容性配置
  jackson: # JSON序列化配置
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式
    default-property-inclusion: NON_NULL # 不为null时序列化
    time-zone: GMT+8
#  redis:  #redis的配置信息
#    host: 127.0.0.1
#    port: 6379
#    database: 2
#    password:
#  session:  #session存储类型
#    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: spring:session

server:
  port: 1224
#  servlet:
#    session:
#      timeout: 1800

# mybatis 相关配置，单独配置，顶格写
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # 指定 xxxMapper.xml的扫描路径



logging:
  level:
    root: info  # 日志的默认级别
    com.learnings.forum: debug  # 指定包下的日志级别
  file:
    path: D:/ASSIGNMENT/code/log-forum  # 反斜杠需要转译，故用斜杠表示
  pattern:
    dateformat: MM-dd HH:mm:ss  # 日期的显示格式


# 项⽬⾃定义相关配置
fox-forum:
  login:
    url: sign-in.html # 未登录状况下强制跳转页面
  index:  # 首页配置节点
    board-num: 9    # 首页中显示的版块个数