spring:
  application:
    name: 论坛系统
  datasource:   # 配置数据源
    url: jdbc:mysql://127.0.0.1:3307/forum_db?characterEncoding=utf8&useSSL=false  # 数据库连接串
    username: root
    password: 000000
    driver-class-name: com.mysql.jdbc.Driver # 数据库连接驱动

# mybatis 相关配置，单独配置，顶格写
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # 指定 xxxMapper.xml的扫描路径

server:
  port: 1224

logging:
  level:
    root: info  # 日志的默认级别
    com.learnings.forum: debug  # 指定包下的日志级别
  file:
    path: D:/ASSIGNMENT/code/log-forum  # 反斜杠需要转译，故用斜杠表示
  pattern:
    dateformat: MM-dd HH:mm:ss  # 日期的显示格式